spring.application.name=rest-crud-demo

spring.datasource.url=jdbc:mysql://localhost:3306/employee_directory
spring.datasource.username=springstudent
spring.datasource.password=springstudent
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#you can also set the custom path  for your swagger-ui and your api-docs


#springdoc.swagger-ui.path=/my-ui.html
#springdoc.api-docs.path=/my-api-docs



#adding custom users name and password to the spring security
spring.security.user.name=subhransu
spring.security.user.password=2302165
spring.main.banner-mode=off


logging.level.org.springframework.jdbc=DEBUG
logging.level.org.springframework.security=DEBUG